# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    crypto_compare_api_base_url: '%env(CRYPTO_COMPARE_API_BASE_URL)%'

services:
    GuzzleHttp\Client: ~
    App\Factory\MockDataFactory: ~
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\DataSaverInterface: '@App\Service\DataSaverService'
    App\Service\Interface\CurrencyDataUpdaterInterface: '@App\Service\CurrencyDataUpdaterService'

    App\Service\CryptoCurrencyApiService:
        arguments:
            $apiBaseUrl: '%crypto_compare_api_base_url%'
            $client: '@GuzzleHttp\Client'
    App\Service\CurrencyDataManagementService:
        arguments:
            $currencyRateRepository: '@App\Repository\CurrencyRateRepository'
            $dataUpdater: '@App\Service\Interface\CurrencyDataUpdaterInterface'
    App\Service\CurrencyDataUpdaterService:
        arguments:
            $apiService: '@App\Service\CryptoCurrencyApiService'
            $currencyRateRepository: '@App\Repository\CurrencyRateRepository'
            $entityManager: '@doctrine.orm.entity_manager'
            $dataSaver: '@App\Service\Interface\DataSaverInterface'
    App\Service\DataSaverService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $currencyRateRepository: '@App\Repository\CurrencyRateRepository'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
